In [1]:
import pandas as pd
import numpy as np

In [2]:
reviews = pd.read_csv('Reviews.csv')

In [3]:
reviews.head(10)

Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   
5   6  B006K2ZZ7K   ADT0SRK1MGOEU                   Twoapennything   
6   7  B006K2ZZ7K  A1SP2KVKFXXRU1                David C. Sullivan   
7   8  B006K2ZZ7K  A3JRGQVEQN31IQ               Pamela G. Williams   
8   9  B000E7L2R4  A1MZYO9TZK0BBI                         R. James   
9  10  B00171APVA  A21BT40VZCCYT4                    Carol A. Reed   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   
5                     0                       0      4  1342051200   
6                     0                       0      5  1340150400   
7                     0                       0      5  1336003200   
8                     1                       1      5  1322006400   
9                     0                       0      5  1351209600   

                                         Summary  \
0                          Good Quality Dog Food   
1                              Not as Advertised   
2                          "Delight" says it all   
3                                 Cough Medicine   
4                                    Great taffy   
5                                     Nice Taffy   
6  Great!  Just as good as the expensive brands!   
7                         Wonderful, tasty taffy   
8                                     Yay Barley   
9                               Healthy Dog Food   

                                                Text  
0  I have bought several of the Vitality canned d...  
1  Product arrived labeled as Jumbo Salted Peanut...  
2  This is a confection that has been around a fe...  
3  If you are looking for the secret ingredient i...  
4  Great taffy at a great price.  There was a wid...  
5  I got a wild hair for taffy and ordered this f...  
6  This saltwater taffy had great flavors and was...  
7  This taffy is so good.  It is very soft and ch...  
8  Right now I'm mostly just sprouting this so my...  
9  This is a very healthy dog food. Good for thei...

In [4]:
def classifier(row):
    if row['Score'] > 3:
        return 'Positive'
    else:
        return 'Negative'

reviews['Response'] = reviews.apply(classifier, axis=1)

Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   
5   6  B006K2ZZ7K   ADT0SRK1MGOEU                   Twoapennything   
6   7  B006K2ZZ7K  A1SP2KVKFXXRU1                David C. Sullivan   
7   8  B006K2ZZ7K  A3JRGQVEQN31IQ               Pamela G. Williams   
8   9  B000E7L2R4  A1MZYO9TZK0BBI                         R. James   
9  10  B00171APVA  A21BT40VZCCYT4                    Carol A. Reed   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   
5                     0                       0      4  1342051200   
6                     0                       0      5  1340150400   
7                     0                       0      5  1336003200   
8                     1                       1      5  1322006400   
9                     0                       0      5  1351209600   

                                         Summary  \
0                          Good Quality Dog Food   
1                              Not as Advertised   
2                          "Delight" says it all   
3                                 Cough Medicine   
4                                    Great taffy   
5                                     Nice Taffy   
6  Great!  Just as good as the expensive brands!   
7                         Wonderful, tasty taffy   
8                                     Yay Barley   
9                               Healthy Dog Food   

                                                Text  Response  
0  I have bought several of the Vitality canned d...  Positive  
1  Product arrived labeled as Jumbo Salted Peanut...  Negative  
2  This is a confection that has been around a fe...  Positive  
3  If you are looking for the secret ingredient i...  Negative  
4  Great taffy at a great price.  There was a wid...  Positive  
5  I got a wild hair for taffy and ordered this f...  Positive  
6  This saltwater taffy had great flavors and was...  Positive  
7  This taffy is so good.  It is very soft and ch...  Positive  
8  Right now I'm mostly just sprouting this so my...  Positive  
9  This is a very healthy dog food. Good for thei...  Positive

In [5]:
import spacy
import nltk
nlp = spacy.load('en_core_web_sm', disable=['parser', 'ner'])

In [6]:
from nltk.tokenize import word_tokenize
import re

In [21]:
def preprocess_text(input_str):
    words = word_tokenize(input_str)
    words = [re.sub(r"[^A-Za-z@]", "", word) for word in words]
    words = [re.sub(r"\S+com", "", word) for word in words]
    words = [re.sub(r"\S+@\S+", "", word) for word in words]
    words = [word for word in words if word!=' ']

    #import nltk stopwords
    stopwords_nltk = nltk.corpus.stopwords.words('english')
    
    #import other lists of stopwords
    with open('stopwords_en.txt', 'r') as f:
        file = f.readlines()
    stopwords = []
    for word in file:
        stopwords.append(word.replace('\n', ''))

    stopwords = stopwords + stopwords_nltk
    stopwords = [s.lower() for s in stopwords]
    
    words = [token.lemma_ for token in nlp(' '.join(words)) if not token.is_punct]
    words = [word.lower() for word in words if word.lower() not in stopwords]
    
    while ' ' in words: words.remove(' ')
    return ' '.join(words)

print(preprocess_text(reviews.iloc[0]['Text']))

buy vitality dog food product find good quality product stew process meat smell labrador finicky product


In [22]:
from sklearn.feature_extraction.text import CountVectorizer

In [23]:
corpus = []
texts = reviews['Text'].tolist()[0:10]
for text in texts:
    corpus.append(preprocess_text(text))
corpus

['buy vitality dog food product find good quality product stew process meat smell labrador finicky product',
 'product arrive label jumbo salted peanuts peanut small sized unsalted error vendor intend represent product jumbo',
 'confection century light pillowy citrus gelatin nuts case filberts cut tiny square liberally coat powdered sugar tiny mouthful heaven chewy flavorful highly mend yummy treat familiar story cs lewis    lion witch wardrobe    treat seduce edmund sell brother sisters witch',
 'secret ingredient robitussin find addition root beer extract order good make cherry soda flavor medicinal',
 'great taffy great price wide assortment yummy taffy delivery quick taffy lover deal',
 'wild hair taffy order pound bag taffy enjoyable flavor watermelon root beer melon peppermint grape complaint bit redblack licoriceflavore piece favorite    kid husband week mend brand taffy delightful treat',
 'saltwater taffy great flavor soft chewy candy individually wrap candy stick happen expe

In [24]:
vectorizer = CountVectorizer(stop_words='english')
vectorizer.fit(corpus)
vector = vectorizer.transform(corpus)

In [25]:
vectorizer.vocabulary_

{'buy': 10,
 'vitality': 122,
 'dog': 27,
 'food': 41,
 'product': 86,
 'good': 44,
 'quality': 88,
 'stew': 112,
 'process': 85,
 'meat': 69,
 'smell': 107,
 'labrador': 60,
 'finicky': 38,
 'arrive': 2,
 'label': 59,
 'jumbo': 57,
 'salted': 97,
 'peanuts': 78,
 'peanut': 77,
 'small': 106,
 'sized': 105,
 'unsalted': 119,
 'error': 31,
 'vendor': 120,
 'intend': 56,
 'represent': 91,
 'confection': 20,
 'century': 14,
 'light': 64,
 'pillowy': 81,
 'citrus': 17,
 'gelatin': 43,
 'nuts': 74,
 'case': 12,
 'filberts': 37,
 'cut': 22,
 'tiny': 117,
 'square': 111,
 'liberally': 62,
 'coat': 18,
 'powdered': 83,
 'sugar': 115,
 'mouthful': 73,
 'heaven': 51,
 'chewy': 16,
 'flavorful': 40,
 'highly': 52,
 'mend': 72,
 'yummy': 131,
 'treat': 118,
 'familiar': 34,
 'story': 114,
 'cs': 21,
 'lewis': 61,
 'lion': 65,
 'witch': 129,
 'wardrobe': 123,
 'seduce': 101,
 'edmund': 29,
 'sell': 102,
 'brother': 9,
 'sisters': 104,
 'secret': 100,
 'ingredient': 55,
 'robitussin': 93,
 'addition

In [26]:
vector.shape

(10, 132)

In [27]:
print(vector.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 2 0 1]
 ...
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [28]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [ ]:
nb.fit(X_train_dtm, train.Score)